version: '3.3'

services:
  chatgpt: 
    build:
      context: .
      dockerfile: Dockerfile
    image: chatgpt:001
    environment:
      - NODE_ENV=Production
    stdin_open: true
    tty: true
    restart: always